User State Migration: Prescreen 1C
codeforboston/windfall-elimination pull request #157
Opened 2020-01-29 01:29 UTC by paavanb

This time, we also dropped the `pensionType` state field since it seemed to not be used or referenced anywhere (probably dead code.)

2020-01-29 01:33 UTC, lady3bean approved these changes
since I was looking as you did it, maybe someone else's review would be valuable too. But I think it looks great!

2020-01-30 04:35 UTC, thadk requested changes
We can merge as-is but it would be nice to restore the warning for the 0 value of the WEP pension.

2020-01-30 04:35 UTC, thadk commented on src/pages/prescreen-1c.tsx
> +  handleDateAwardedChange = (value: Date) => {
Squeaky clean!

2020-01-30 04:35 UTC, thadk commented on src/pages/prescreen-1c.tsx
> +        else setPensionAmount(0)
This changed from empty with a red placeholder:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/283343/73420065-5e9a2a00-42ef-11ea-8669-2a07400243c1.png">

to a zero by default:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/283343/73420015-33173f80-42ef-11ea-9d50-e35f3620223b.png">

Should we handle this as a special case on the front end or do we want to keep it null/undefined until they enter something. 

We want to call out it as strange if they do not put a value in when they said they have some sort of government pension/account.

2020-01-30 04:35 UTC, thadk commented on src/pages/prescreen-1c.tsx
> +                    defaultValue={pensionAmount || 0}
See above.

2020-02-04 23:13 UTC, paavanb commented on src/pages/prescreen-1c.tsx
> +                    defaultValue={pensionAmount || 0}
Easy fix: get rid of the `||`!

2020-02-05 00:36 UTC, thadk approved these changes

2020-02-05 00:36 UTC, merged